const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const stages=[
{name:"1. SOLICITAÇÃO",area:"Comercial",total:"R$ 320.500,00",deals:[["COT-2026-00135","AgroTenk","Caixa 500L","R$ 85.000,00","12/05","GS"],["COT-2026-00136","Hidro Campo","Tanque 1000L","R$ 120.000,00","15/05","JL"]]},
{name:"2. ANÁLISE CRÍTICA",area:"Engenharia",total:"R$ 250.000,00",deals:[["COT-2026-00131","XYZ S/A","Tampa 450mm","R$ 50.000,00","11/05","JL"],["COT-2026-00132","Mega Agro","Reservatório 2000L","R$ 200.000,00","13/05","MR"]]},
{name:"3. DEVOLUTIVA P/ COMERCIAL",area:"Engenharia",total:"R$ 180.000,00",deals:[["COT-2026-00129","Indústria Forte","Caixa 310L","R$ 80.000,00","14/05","MR"],["COT-2026-00130","Hidro Norte","Tanque 1500L","R$ 100.000,00","15/05","CF"]]},
{name:"4. FORMAÇÃO DE CUSTOS",area:"Comercial",total:"R$ 210.000,00",deals:[["COT-2026-00126","Química Sul","Tanque 3000L","R$ 160.000,00","10/05","CF"],["COT-2026-00127","Metalúrgica JN","Palete Contenção","R$ 50.000,00","11/05","GS"]]},
{name:"5. APROVAÇÃO DE CUSTOS",area:"Custos",total:"R$ 250.000,00",deals:[["COT-2026-00123","PetroVale","Tanque 5000L","R$ 250.000,00","09/05","DR"],["COT-2026-00128","AgroMax","Reservatório 1000L","R$ 65.000,00","10/05","MR"]]},
{name:"6. APROVAÇÃO DA DIREÇÃO",area:"Direção",total:"R$ 250.000,00",deals:[["COT-2026-00124","Transportes BR","Caixa 200L","R$ 250.000,00","08/05","DR"]]},
{name:"7. ENVIADA / FINALIZADA",area:"Comercial",total:"R$ 465.000,00",deals:[["COT-2026-00122","ConstruLider","Caixa 200L","R$ 35.000,00","Enviada","GS"],["COT-2026-00121","AgroVale","Tanque 2000L","R$ 95.000,00","Enviada","JL"]]}
];
const quote={id:"COT-2026-00131",cliente:"XYZ S/A",produto:"Tampa 450mm",quantidade:"1.000 un",prazo:"30 dias",valor:"R$ 50.000,00",vendedor:"Giovanna S.",stage:1};
const notifications=[
{title:"Cotação atualizada",text:"COT-2026-00131 avançou para Análise Crítica.",time:"Hoje, 10:21"},
{title:"Novo compromisso",text:"Reunião de alinhamento adicionada ao calendário.",time:"Hoje, 09:48"},
{title:"Documento recebido",text:"Especificação_Técnica.pdf foi anexado à cotação.",time:"Ontem, 16:32"}
];
let currentView="dashboard",calendarDate=new Date(2026,4,1),events=JSON.parse(localStorage.getItem("demoEvents")||"[]");

function renderPipeline(){ $("#pipeline").innerHTML=stages.map((s,i)=>`<div class="stage"><div class="stage-head"><strong>${s.name}</strong><span>(${s.area})</span><div class="stage-total"><span>${s.deals.length} Cotações</span><b>${s.total}</b></div></div>${s.deals.map(d=>`<div class="deal ${d[0]===quote.id?"selected":""}" data-id="${d[0]}"><strong>${d[0]}</strong><p>Cliente: ${d[1]}<br>Produto: ${d[2]}<br>${d[4]==="Enviada"?"Valor final":"Valor estimado"}: ${d[3]}</p><span class="due ${i>=4&&i<6?"red":""} ${d[4]==="Enviada"?"sent":""}">${d[4]==="Enviada"?"Enviada":"Prazo: "+d[4]}</span><span class="initial">${d[5]}</span></div>`).join("")}<button class="new-stage" data-stage="${i}">+ Nova Cotação</button></div>`).join("");$$(".deal").forEach(e=>e.onclick=()=>selectDeal(e.dataset.id));$$(".new-stage").forEach(e=>e.onclick=()=>openQuoteModal());}
function renderQuote(){ $("#detailTitle").textContent=quote.id;$("#stageBadge").textContent=stages[quote.stage].name.replace(/^\d+\.\s/,"")+" - "+stages[quote.stage].area.toUpperCase();$("#quoteSummary").innerHTML=[["Cliente",quote.cliente],["Produto",quote.produto],["Quantidade",quote.quantidade],["Prazo solicitado",quote.prazo],["Valor estimado",quote.valor],["Vendedor",quote.vendedor]].map(x=>`<div class="summary-item"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");const names=["Solicitação","Análise Crítica","Devolutiva","Formação de Custos","Aprovação de Custos","Aprovação da Direção","Enviada / Finalizada"];$("#progress").innerHTML=names.map((n,i)=>`<div class="step ${i<quote.stage?"done":""} ${i===quote.stage?"current":""}"><div class="dot">${i===0&&i<quote.stage?"✓":i+1}</div><strong>${n}</strong><small>${i===quote.stage?"Em andamento":i<quote.stage?"Concluído":"Aguardando"}</small></div>`).join("");renderTab("resumo");}
function renderTab(tab){$$(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab));const c={resumo:`<div class="data-grid"><div><h4>DADOS TÉCNICOS</h4><div class="field"><span>Produto tecnicamente viável?</span><b class="pill">Sim</b></div><div class="field"><span>Necessita desenvolvimento?</span><b class="pill partial">Parcial</b></div><div class="field"><span>Ferramental necessário?</span><b class="pill">Sim</b></div><div class="field"><span>Matéria-prima indicada</span><b class="input-look">PEAD</b></div><div class="field"><span>Processo</span><b class="input-look">Rotomoldagem</b></div><div class="field"><span>Peso estimado da peça</span><b class="input-look">2,45 kg</b></div></div><div><h4>PARÂMETROS</h4><div class="field"><span>Espessura média</span><b class="input-look">5 mm</b></div><div class="field"><span>Cor</span><b class="input-look">Preta</b></div><div class="field"><span>Quantidade mínima</span><b class="input-look">500 un</b></div><div class="field"><span>Prazo de desenvolvimento</span><b class="input-look">20 dias</b></div><div class="field"><span>Prazo de fabricação</span><b class="input-look">10 dias</b></div></div><div><h4>OBSERVAÇÕES TÉCNICAS</h4><div class="obs">Projeto viável com ajustes no reforço da tampa. Ferramental novo necessário. Sugestão de revisão no encaixe da tampa para melhor vedação.</div><div class="files"><strong>Anexos</strong><div class="file">▧ Desenho_Tampa450mm.pdf &nbsp; ↓</div><div class="file">▧ Especificação_Técnica.pdf &nbsp; ↓</div></div></div></div>`,
analise:`<div class="tab-panel"><h4>Análise crítica de engenharia</h4><p>Validação técnica da peça, ferramental, matéria-prima, tolerâncias e requisitos do cliente.</p><label><input type="checkbox" checked> Produto tecnicamente viável</label><br><label><input type="checkbox"> Requer ajuste no projeto</label></div>`,
devolutiva:`<div class="tab-panel"><h4>Devolutiva para Comercial</h4><textarea style="width:100%;min-height:130px;border:1px solid #dce3eb;border-radius:5px;padding:10px;background:var(--card);color:var(--text)">Projeto viável com ajustes no reforço da tampa. Ferramental novo necessário.</textarea><div class="quote-actions"><button class="primary" id="sendFeedback">Enviar devolutiva</button></div></div>`,
custos:`<div class="tab-panel"><h4>Formação de custos</h4><div class="field"><span>Matéria-prima</span><b>R$ 18.500,00</b></div><div class="field"><span>Ferramental</span><b>R$ 7.800,00</b></div><div class="field"><span>Mão de obra</span><b>R$ 9.400,00</b></div><div class="field"><span>Margem e despesas</span><b>R$ 14.300,00</b></div><hr><div class="field"><span><strong>Total estimado</strong></span><b>R$ 50.000,00</b></div></div>`,
aprovacoes:`<div class="tab-panel"><h4>Fluxo de aprovações</h4><p>✓ Análise de engenharia — João Lima</p><p>○ Aprovação de custos — Marina Rocha</p><p>○ Aprovação da direção — Diretoria</p></div>`,
anexos:`<div class="tab-panel"><h4>Documentos</h4><div class="file">▧ Desenho_Tampa450mm.pdf — 2,4 MB</div><div class="file">▧ Especificação_Técnica.pdf — 840 KB</div></div>`,
atividades:`<div class="tab-panel"><h4>Atividades</h4><p><b>05/05 10:21</b> — Etapa alterada para Engenharia por João Lima.</p><p><b>05/05 09:16</b> — Documento adicionado por Giovanna Sales.</p></div>`,
historico:`<div class="tab-panel"><h4>Histórico da cotação</h4><p>05/05 — Solicitação recebida</p><p>05/05 — Encaminhada para análise crítica</p><p>05/05 — João Lima assumiu a etapa de engenharia</p></div>`};$("#tabContent").innerHTML=c[tab]||"";$("#sendFeedback")?.addEventListener("click",()=>moveQuote(1));}
function selectDeal(id){const found=stages.flatMap((s,i)=>s.deals.map(d=>({d,i}))).find(x=>x.d[0]===id);if(!found)return;quote.id=found.d[0];quote.cliente=found.d[1];quote.produto=found.d[2];quote.valor=found.d[3];quote.stage=found.i;renderPipeline();renderQuote();}
function moveQuote(dir){const next=Math.max(0,Math.min(6,quote.stage+dir));if(next===quote.stage)return;quote.stage=next;renderPipeline();renderQuote();addNotification(`Cotação ${quote.id} movimentada`,`Etapa atual: ${stages[next].name}.`);}
function addNotification(title,text){notifications.unshift({title,text,time:"Agora"});renderNotifications();}
function renderNotifications(){const list=notifications.slice(0,6);$("#notificationList").innerHTML=list.map(n=>`<div class="notif"><span class="notif-dot"></span><div><strong>${n.title}</strong><p>${n.text}</p><time>${n.time}</time></div></div>`).join("");$("#notificationCount").textContent=Math.min(list.length,9);}
function switchView(view){currentView=view;$$(".view").forEach(v=>v.classList.add("hidden"));$("#view-"+view).classList.remove("hidden");$$(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));const titles={dashboard:"Dashboard - Processo de Cotação",calendario:"Calendário 2026",pagamentos:"Pagamentos",configuracoes:"Configurações"};$("#pageTitle").textContent=titles[view];if(view==="calendario")renderCalendar();if(view==="pagamentos")renderPayments();if(view==="configuracoes")loadSettings();}
function openQuoteModal(){$("#modal").classList.remove("hidden");$("#quoteForm").reset();}
function closeQuoteModal(){$("#modal").classList.add("hidden");}
function renderCalendar(){const y=2026,m=calendarDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=first.getDay();$("#calendarMonth").textContent=first.toLocaleDateString("pt-BR",{month:"long",year:"numeric"}).replace(/^./,x=>x.toUpperCase());let cells="";for(let i=0;i<42;i++){const d=i-start+1;if(d<1||d>days){cells+=`<div class="day other"></div>`;continue}const date=`2026-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,today=new Date(),isToday=today.getFullYear()===2026&&today.getMonth()===m&&today.getDate()===d;const ev=events.filter(e=>e.date===date);cells+=`<div class="day ${isToday?"today":""}"><div class="day-number">${d}</div>${ev.map(e=>`<div class="event" title="Clique para excluir" data-event="${e.id}"><button>×</button><b>${e.time||""} ${e.title}</b><small>${e.person||""}</small></div>`).join("")}</div>`}$("#calendarGrid").innerHTML=cells;$$(".event").forEach(e=>e.onclick=()=>{events=events.filter(x=>x.id!==e.dataset.event);localStorage.setItem("demoEvents",JSON.stringify(events));renderCalendar();});}
function renderPayments(){const rows=stages.flatMap((s,i)=>s.deals.map(d=>({id:d[0],cliente:d[1],valor:parseBR(d[3]),stage:i})));const total=rows.reduce((a,r)=>a+r.valor,0),paid=rows.filter(r=>r.stage===6).reduce((a,r)=>a+r.valor,0),open=total-paid,profit=total*.2;$("#paymentKpis").innerHTML=[["Total das cotações",money(total)],["Pago / finalizado",money(paid)],["Em aberto",money(open)],["Lucro projetado (20%)",money(profit)]].map(k=>`<div class="kpi"><span>${k[0]}</span><strong>${k[1]}</strong></div>`).join("");$("#paymentTable").innerHTML=`<div class="payment-row head"><span>COTAÇÃO</span><span>CLIENTE</span><span>VALOR + 20%</span><span>STATUS</span><span>PAGAMENTO</span></div>`+rows.map(r=>{const sale=r.valor*1.2,paidStatus=r.stage===6;let method=paidStatus?"Pago em 15/05/2026":r.stage===0?"Até 30 dias":r.stage===1||r.stage===2?"Pagamento imediato":r.stage>=3?"Antecipado":"A definir";return `<div class="payment-row"><span><b>${r.id}</b></span><span>${r.cliente}</span><span>${money(sale)}</span><span><b class="${paidStatus?"status-paid":r.stage===0?"status-open":"status-immediate"}">${paidStatus?"Pago":"Pendente"}</b></span><span>${method}</span></div>`}).join("");drawChart(rows);}
function parseBR(v){return typeof v==="number"?v:Number(String(v).replace(/[^\d,]/g,"").replace(/\./g,"").replace(",","."));}function money(n){return n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});}
function drawChart(rows){const canvas=$("#profitChart"),ctx=canvas.getContext("2d"),rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=270*dpr;ctx.scale(dpr,dpr);const w=rect.width,h=270,pad=30,max=Math.max(...rows.map(r=>r.valor*1.2),1),bar=(w-pad*2)/rows.length*.62;ctx.font="9px Inter, Arial";rows.forEach((r,i)=>{const x=pad+i*((w-pad*2)/rows.length)+(w-pad*2)/rows.length*.19,val=r.valor*1.2,bh=(val/max)*(h-55),y=h-30-bh;ctx.fillStyle=getComputedStyle(document.body).getPropertyValue("--blue");ctx.fillRect(x,y,bar,bh);ctx.fillStyle=getComputedStyle(document.body).getPropertyValue("--muted");ctx.save();ctx.translate(x+bar/2,h-15);ctx.rotate(-.55);ctx.textAlign="right";ctx.fillText(r.id.replace("COT-2026-",""),0,0);ctx.restore();ctx.fillText(money(val),x,y-5);});}
function loadSettings(){const dark=localStorage.getItem("darkMode")==="1";$("#darkModeToggle").checked=dark;$("#branchSetting").value=localStorage.getItem("branch")||$("#branchChip").textContent.replace("Filial: ","");$("#notifToggle").checked=localStorage.getItem("notifEnabled")!=="0";}
function applyDark(v){document.body.classList.toggle("dark",v);localStorage.setItem("darkMode",v?"1":"0");}
function openEventModal(){const today=`2026-${String(calendarDate.getMonth()+1).padStart(2,"0")}-01`;$("#eventForm").reset();$("#eventForm [name=date]").value=today;$("#eventModal").classList.remove("hidden");}
function closeEventModal(){$("#eventModal").classList.add("hidden");}

$("#loginForm").addEventListener("submit",e=>{e.preventDefault();const email=$("#loginEmail").value.trim(),pass=$("#loginPassword").value,branch=$("#loginBranch").value;if(email&&pass.length>=4&&branch){sessionStorage.setItem("demoLoggedIn","1");localStorage.setItem("branch",branch);$("#loginScreen").classList.add("hidden");$("#branchChip").textContent="Filial: "+branch;$("#userBranch").textContent="Comercial • "+branch;}else $("#loginError").style.display="block";});
if(sessionStorage.getItem("demoLoggedIn")==="1")$("#loginScreen").classList.add("hidden");
const savedBranch=localStorage.getItem("branch");if(savedBranch){$("#branchChip").textContent="Filial: "+savedBranch;$("#userBranch").textContent="Comercial • "+savedBranch;}
$$("[data-view]").forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$(".tab").forEach(b=>b.onclick=()=>renderTab(b.dataset.tab));renderPipeline();renderQuote();renderNotifications();
$("#moveBtn").onclick=()=>moveQuote(1);$("#moveBackBtn").onclick=()=>moveQuote(-1);$("#newQuoteBtn").onclick=openQuoteModal;$("#quickAdd").onclick=openQuoteModal;$("#closeModal").onclick=closeQuoteModal;$("#cancelModal").onclick=closeQuoteModal;$("#closeEventModal").onclick=closeEventModal;$("#cancelEvent").onclick=closeEventModal;
$("#quoteForm").addEventListener("submit",e=>{e.preventDefault();const fd=new FormData(e.target),id=`COT-2026-${String(137+stages[0].deals.length).padStart(5,"0")}`,val=Number(fd.get("valor"));stages[0].deals.push([id,fd.get("cliente"),fd.get("produto"),money(val),"18/05","GR"]);closeQuoteModal();selectDeal(id);addNotification("Nova cotação criada",`${id} foi adicionada à etapa Solicitação.`);});
$("#notificationBtn").onclick=()=>$("#notificationsPopover").classList.toggle("hidden");$("#markRead").onclick=()=>{$("#notificationCount").textContent="0";$("#notificationsPopover").classList.add("hidden");};
$("#logoutBtn").onclick=()=>{sessionStorage.removeItem("demoLoggedIn");$("#loginScreen").classList.remove("hidden");};
$("#prevMonth").onclick=()=>{if(calendarDate.getMonth()>0){calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar();}};$("#nextMonth").onclick=()=>{if(calendarDate.getMonth()<11){calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar();}};$("#todayBtn").onclick=()=>{calendarDate=new Date(2026,4,1);renderCalendar();};$("#newEventBtn").onclick=openEventModal;
$("#eventForm").addEventListener("submit",e=>{e.preventDefault();const fd=new FormData(e.target);events.push({id:Date.now().toString(),title:fd.get("title"),date:fd.get("date"),time:fd.get("time"),person:fd.get("person"),description:fd.get("description")});localStorage.setItem("demoEvents",JSON.stringify(events));closeEventModal();renderCalendar();addNotification("Compromisso criado",`${fd.get("title")} foi adicionado ao calendário.`);});
$("#darkModeToggle").onchange=e=>applyDark(e.target.checked);$("#branchSetting").onchange=e=>{localStorage.setItem("branch",e.target.value);$("#branchChip").textContent="Filial: "+e.target.value;$("#userBranch").textContent="Comercial • "+e.target.value;};$("#notifToggle").onchange=e=>localStorage.setItem("notifEnabled",e.target.checked?"1":"0");
$("#reportBtn").onclick=()=>switchView("pagamentos");$("#moreBtn").onclick=()=>$("#notificationsPopover").classList.toggle("hidden");$("#editBtn").onclick=openQuoteModal;$("#createTask").onclick=()=>addNotification("Tarefa criada","Tarefa de acompanhamento adicionada à cotação.");$("#addTask").onclick=()=>addNotification("Tarefa criada","Nova tarefa adicionada à cotação.");$("#addNote").onclick=()=>{const n=prompt("Digite a nota:");if(n)$("#noteText").textContent=n;};
window.addEventListener("resize",()=>{if(currentView==="pagamentos")drawChart(stages.flatMap((s,i)=>s.deals.map(d=>({id:d[0],cliente:d[1],valor:parseBR(d[3]),stage:i}))));});
